### ISSUE TITLE
StreamElements donations are not pulled 

### ISSUE THREAD

**Issue by mensae** [lokkelvin2/tacotron2-tts-GUI#1]
Hello,

I've tried to download your application. I've been able to correctly plug the pretrained models, but apparently the donations from StreamElements are not pulled. 

Moreover, I would like to understand how to properly train my own model(s): could you point me to some instructions?

Thanks.

**Comment by lokkelvin2** [comment]
Are you using the exe file or building from source? I just tested the exe and donation TTS is working as they should. Maybe you can try putting in donations [manually](https://streamelements.com/dashboard/tipping/list) and see if they pop up on the GUI.

For training the NVIDIA tacotron2 & waveglow models your best bet is to look at the original repos [one](https://github.com/NVIDIA/tacotron2) and [two](https://github.com/NVIDIA/waveglow). The authors provide some examples on training. Unfortunately I'm not an expert in finetuning models so thats all the advice I have for you.

**Comment by lokkelvin2** [comment]
Closing because there has been no response from the original author.
