### ISSUE TITLE
TTS playback on reference models is too fast

### ISSUE THREAD

**Issue by githubuser720** [lokkelvin2/tacotron2-tts-GUI#6]
> Hi, I have done that but whenever I try to generate a TTS the output sounds really bad, e.g. it's like a blib, see video:
https://www.youtube.com/watch?v=vcGLX1OtjyM& at 0:03 you should hear it.

_Originally posted by @maandagdev in https://github.com/lokkelvin2/tacotron2-tts-GUI/issues/4#issuecomment-752023162_

I am also running into this.

**Comment by lottev1991** [comment]
I know I'm years late and that this issue has been closed, but to anyone reading who's still interested: adding ``allowedchanges=0`` in ``pygame.mixer.init()`` fixed it for me.
